name: ci

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - uses: docker-practice/actions-setup-docker@master
      - uses: azure/docker-login@v1
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: khs1994
          password: ${{ secrets.GHCR_IO_TOKEN }}
      - run: |
          export GITHUB_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)

          # DOCKER_PUSH="--load"
          DOCKER_PUSH="--push"
          DOCKER_LATEST_TAG="dev"

          if ! [ $GITHUB_EVENT_NAME = 'workflow_dispatch' ];then
            DOCKER_IMAGE="-t khs1994/acme:${GITHUB_TAG} -t ${REGISTRY_MIRROR}/khs1994/acme:${GITHUB_TAG}"
            DOCKER_PUSH="--push"
            DOCKER_LATEST_TAG="latest"
          fi

          docker buildx build \
            -t khs1994/acme:${DOCKER_LATEST_TAG} \
            -t ${REGISTRY_MIRROR}/khs1994/acme:${DOCKER_LATEST_TAG} \
            ${DOCKER_IMAGE} \
            ${DOCKER_PUSH} \
            --cache-from=ghcr.io/khs1994/acme:cache \
            --cache-to=ghcr.io/khs1994/acme:cache \
            .
        env:
          REGISTRY_MIRROR: ghcr.io
          GITHUB_EVENT_NAME: ${{github.event_name}}
        name: Build docker image
